---
apiVersion: "v2"
name: "sonarr"
description: "A Sonarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.2.2"
# renovate: image=ghcr.io/linuxserver/sonarr
appVersion: "4.0.16.2944-ls303@sha256:37be832b78548e3f55f69c45b50e3b14d18df1b6def2a4994258217e67efb1a1"
icon: "https://avatars.githubusercontent.com/u/1082903"
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Remove the digest from the version label
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
