---
apiVersion: v2
name: servarr-single
description: A Helm library chart for shared Servarr Single configurations and templates.
type: library
version: 0.1.14
appVersion: "1.0.0"
icon: "https://raw.githubusercontent.com/Servarr/Wiki/refs/heads/master/assets/servarr/servarr_dark_128.png"
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Set service type to ClusterIP in values.yaml
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/Panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
