apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prowlarr.fullname" . }}-apikey-sync
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prowlarr.fullname" . }}-apikey-sync
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prowlarr.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "prowlarr.fullname" . }}-apikey-sync
  apiGroup: rbac.authorization.k8s.io
