{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "prowlarr.fullname" . }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
---
{{- end }}
{{- if and .Values.persistence.backups.enabled (not .Values.persistence.backups.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-backups" (include "prowlarr.fullname" .) }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistence.backups.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.backups.storageClass | quote }}
  {{- else if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.backups.accessMode | default .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size | quote }}
{{- end }}

