{{- define "servarr-single.configmap" -}}
{{- if .Values.syncApiKey.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servarr-single.syncApiKeyScriptName" . }}
  labels:
    {{- include "servarr-single.labels" . | nindent 4 }}
data:
  sync-api-key.sh: |
{{ .Files.Get "scripts/sync-api-key.sh" | indent 4 }}
...
{{- end }}
{{- end }}
