{{- define "servarr-single.rbac" -}}
{{- if .Values.syncApiKey.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "servarr-single.secretsSyncRoleName" . }}
  labels:
    {{- include "servarr-single.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "servarr-single.secretsSyncRoleName" . }}
  labels:
    {{- include "servarr-single.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "servarr-single.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "servarr-single.secretsSyncRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
...
{{- end }}
{{- end }}
