---
apiVersion: "v2"
name: "prowlarr"
description: "A Prowlarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.4.15"
# renovate: image=ghcr.io/linuxserver/prowlarr
appVersion: "2.3.0.5236-ls135@sha256:d3e9307b320b6772749a2cf8fc2712e9e824c4930b034680ad4d08a9e2f25884"
icon: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/refs/heads/develop/Logo/1024.png"
dependencies:
  - name: servarr-single
    version: 0.1.15
    repository: file://../servarr-single
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump servarr-single dependency to 0.1.15
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/Panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
