---
apiVersion: "v2"
name: "prowlarr"
description: "A Prowlarr Helm chart for Kubernetes."
type: "application"
version: "0.1.0"
# renovate: image=ghcr.io/linuxserver/prowlarr
appVersion: "2.3.0.5236-ls134"
icon: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/refs/heads/develop/Logo/1024.png"
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of Prowlarr chart version 0.1.0
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/Panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
