---
apiVersion: "v2"
name: "prowlarr"
description: "A Prowlarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.4.6"
# renovate: image=ghcr.io/linuxserver/prowlarr
appVersion: "2.3.0.5236-ls134@sha256:67a8aaedcfd6989f3030b937a6a07007310b1dfc7ee8df16d2cbfa48d1c1158c"
icon: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/refs/heads/develop/Logo/1024.png"
dependencies:
  - name: servarr-single
    version: 0.1.6
    repository: file://../servarr-single
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump servarr-single dependency to 0.1.6
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/Panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
