---
apiVersion: "v2"
name: "prowlarr"
description: "A Prowlarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.1.2"
# renovate: image=ghcr.io/linuxserver/prowlarr
appVersion: "2.3.0.5236-ls134@sha256:aaaaaaa"
icon: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/refs/heads/develop/Logo/1024.png"
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Set default port and add environment variables to values.yaml
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/Panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
